export * from '@/pages/admin/dashboard'
export * from '@/pages/admin/profile'
export * from '@/pages/admin/user-master'
export * from '@/pages/admin/add-user-master'
export * from '@/pages/admin/teacher-master'
export * from '@/pages/admin/student-master'


export * from '@/pages/admin/customer-master'
export * from '@/pages/admin/customer-product-master'
export * from '@/pages/admin/product-master'
export * from '@/pages/admin/branch-master'
export * from '@/pages/admin/staff-master'
export * from '@/pages/admin/add-staff-payout-master'
export * from '@/pages/admin/staff-payout-master'
export * from '@/pages/admin/walkin-customer-master'
export * from '@/pages/admin/recovery-master'
export * from '@/pages/admin/staff-report-master'
export * from '@/pages/admin/expired-customer-product'
export * from '@/pages/admin/edit-customer-product'
export * from '@/pages/admin/edit-expired-customer-product-master'
