export * from '@/pages/admin/dashboard'
export * from '@/pages/admin/profile'
export * from '@/pages/admin/user-master'
export * from '@/pages/admin/add-user-master'
export * from '@/pages/admin/teacher-master'
export * from '@/pages/admin/student-master'
export * from '@/pages/admin/admin-notice-master'
export * from '@/pages/admin/student-report-master'
